apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo-list
  template:
    metadata:
      labels:
        app: react-todo-list
    spec:
      containers:
      - name: react-todo-list
        image: vivekayawale/react-todo-list:latest
        ports:
        - containerPort: 3000

