apiVersion: v1
kind: Service
metadata:
  name: react-todo-list-service
spec:
  type: NodePort
  selector:
    app: react-todo-list
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001

